import './globals.css'
import { Inter } from 'next/font/google'
// import Header from './Components/Header'
// import Banner from './Components/Bannar'
// import BannerBottom from './Components/BannerBottom'
// import Footer from './Components/footer';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

        {children}

        </body>
    </html>
  )
}
